name: Regression ARM
on:
  push:
    branches:
      - arm_test
jobs:
  regress_arm:
    name: ARM PG${{ matrix.pg }} ${{ matrix.build_type }}
    runs-on: 'ubuntu-18.04'
    strategy:
      matrix:
        pg: [ 12 ]
        build_type: [ Debug ]

      fail-fast: true
    env:
      MAKE_JOBS: 6
      DEBIAN_FRONTEND: noninteractive

    steps:
    - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset

    - uses: actions/checkout@v1

    - name: Build & Test
      uses: docker://multiarch/ubuntu-core:arm64-focal
      with:
        args: >
          sh -c "
            apt update &&
            apt install -y libssl-dev make postgresql-common gnupg systemd-coredump gdb &&
            yes | /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh &&
            apt install -y postgresql-${{ matrix.pg }} postgresql-server-dev-${{ matrix.pg }} cmake sudo libkrb5-dev
            ./bootstrap -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DREGRESS_CHECKS=OFF &&
            make -C build &&
            make -C build install &&
            chown -R postgres:postgres . &&
            sudo -u postgres make -C build -k regresscheck || echo 'bt full' | sudo echo coredumpctl gdb
          "

    - name: Show regression diffs
      if: failure()
      run: |
        find . -name regression.diffs -exec cat {} + > regression.log
        find . -name postmaster.log -exec cat {} + > postgres.log
        cat regression.log

    - name: Save regression diffs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: Regression diff ${{ matrix.pg }}
        path: regression.log

    - name: Save postmaster.log
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: PostgreSQL log ${{ matrix.pg }}
        path: postgres.log

#    - name: Slack Notification
#      if: failure() && github.event_name != 'pull_request'
#      env:
#        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#        SLACK_COLOR: '#ff0000'
#        SLACK_USERNAME: GitHub Action
#        SLACK_TITLE: Regression ARM PG${{ matrix.pg }} ${{ job.status }}
#        SLACK_MESSAGE: ${{ github.event.head_commit.message }}
#      uses: rtCamp/action-slack-notify@v2.0.2
